name: setup_buildx_private_registry

description: This action logs into a private registry and sets up buildx

inputs:
  REGISTRY:
    description: 'Container registry to log into'
    required: true
  REGISTRY_USER:
    description: 'User for Auth'
    required: true
  REGISTRY_PASSWD:
    description: 'User password for Auth'
    required: true

runs:
  using: composite
  steps:
    - name: Login to private # to pull (cached) base image
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.REGISTRY }}
        username: ${{ inputs.REGISTRY_USER }}
        password: "${{ inputs.REGISTRY_PASSWD }}"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=${{ inputs.REGISTRY }}/moby/buildkit:buildx-stable-1
