name: install_cli_login_aws

description: This action installs the aws cli and logs in with provided role

inputs:
  AWS_REGION:
    description: 'AWS resource region'
    required: true
    type: string
    default: eu-central-1
  AWS_ROLE:
    description: 'ARN of IAM role which will be assumed'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install aws cli
      shell: bash
      run: |
        pip install awscli
    - name: Login AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE }}
