name: <app> - build_container_image

on:
  workflow_call:
  workflow_run:
    workflows:
      -  <app> - check_for_new_version
    branches:
      - $default-branch
    types:
      - completed

env:
  GIT_SUBDIR: <app>

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  debug:
    runs-on:
      - self-hosted
    steps:
      - name: print if new app version found
        run: echo "<app>_NEW_VERSION_FOUND value is ${{ vars.<app>_NEW_VERSION_FOUND }}"
  build-image:
    runs-on:
      - self-hosted
    needs: debug
    if: ${{ vars.<app>_NEW_VERSION_FOUND == 'true' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."${{ secrets.FORGEJO_REGISTRY01 }}"]
              http = false
              insecure = false
      - name: extract metadata for the container image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ secrets.FORGEJO_REGISTRY01 }}/${{ secrets.FORGEJO_OWNER01 }}/arc-${{ env.GIT_SUBDIR }}"
      - name: login to forgejo
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.FORGEJO_REGISTRY01 }}
          username: ${{ secrets.FORGEJO_USER01 }}
          password: ${{ secrets.FORGEJO_USER01_PAT }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ env.GIT_SUBDIR }}"
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            "${{ secrets.FORGEJO_REGISTRY01 }}/${{ secrets.FORGEJO_OWNER01 }}/arc-${{ env.GIT_SUBDIR }}:latest"
            "${{ secrets.FORGEJO_REGISTRY01 }}/${{ secrets.FORGEJO_OWNER01 }}/arc-${{ env.GIT_SUBDIR }}:${{ vars.<app>_VERSION }}"
