name: get-latest-tag-update-timestamp-dockerhub

description: Checks if the latest tag of a DockerHub repository has been updated in the past 24 hours and triggers a GitHub dispatch event if updated.

inputs:
  APPLICATION:
    description: 'Application for which to update repo var APPLICATION_LAST_UPDATED'
    required: true
    type: string
  DOCKERHUB_REPO:
    description: 'DockerHub repo (e.g., library/nginx)'
    required: true
    type: string
  GITHUB_REPO:
    description: 'GitHub repo to trigger (e.g., example/example)'
    required: true
    type: string
  GITHUB_PAT_DEFAULT:
    description: 'Personal Access Token with repo scope'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Check tag:latest update
      id: check-update
      shell: bash
      run: |
        REPO="${{ inputs.DOCKERHUB_REPO }}"
        LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/tags/latest" | jq -r '.last_updated')

        if [ "$LATEST_TAG" == "null" ]; then
          echo "Failed to fetch latest tag information" >&2
          exit 1
        fi

        LAST_UPDATED_TIMESTAMP=$(date -d "$LATEST_TAG" +%s)
        CURRENT_TIMESTAMP=$(date +%s)
        DIFF=$((CURRENT_TIMESTAMP - LAST_UPDATED_TIMESTAMP))
        THRESHOLD=$((24 * 60 * 60))

        echo "LAST_UPDATED_TIMESTAMP=$LAST_UPDATED_TIMESTAMP" >> $GITHUB_ENV

        echo "$DIFF"
        echo "$THRESHOLD"

        if [ "$THRESHOLD" -le "$DIFF" ]; then
          echo "updated=true" >> $GITHUB_ENV
        else
          echo "updated=false" >> $GITHUB_ENV
        fi

    - name: Update repo var
      shell: bash
      run: |
        curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.GITHUB_PAT_DEFAULT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d "{\"name\":\"${{ inputs.APPLICATION }}_LATEST_UPDATE\",\"value\":\"${{ env.LAST_UPDATED_TIMESTAMP }}\"}" \
          https://api.github.com/repos/${{ inputs.GITHUB_REPO }}/actions/variables/${{ inputs.APPLICATION }}_LATEST_UPDATE

    - name: Trigger GitHub dispatch
      if: env.updated == 'true'
      shell: bash
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.GITHUB_PAT_DEFAULT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d "{\"event_type\":\"trigger-wf-pushImage2Registry-${{ inputs.APPLICATION }}\"}" \
          https://api.github.com/repos/${{ inputs.GITHUB_REPO }}/dispatches
