name: build_push

on:
  workflow_call:
    inputs:
      APPLICATION:
        description: 'Application for which to build container image'
        required: true
        type: string
      VERSION:
        description: 'Application version'
        required: true
        type: string
      BUILD_ARGS:
        description: 'Build arguments'
        required: false
        type: string
        default: ''
      PUSH_TO_PUBLIC:
        description: 'Push image to public registry'
        required: false
        type: boolean
        default: false
      PUSH_TO_PRIVATE:
        description: 'Push image to private registry'
        required: false
        type: boolean
        default: true
      OWNER:
        description: 'Registry owner'
        required: false
        type: string
        default: ''
      REGISTRY_PRIVATE:
        description: 'Private registry URI:PORT'
        required: true
        type: string
      REGISTRY_PRIVATE_PULL:
        description: 'Private registry URI:PULL_PORT'
        required: true
        type: string
      REGISTRY_PUBLIC:
        description: 'Public registry URI'
        required: false
        type: string
    secrets:
      REGISTRY_PRIVATE_USER:
        required: true
      REGISTRY_PRIVATE_PASSWD:
        required: true
      REGISTRY_PUBLIC_USER:
        required: false
      REGISTRY_PUBLIC_PASSWD:
        required: false

jobs:

  ## PUBLIC ##

  build-image-push-public:
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        include:
          - platform: amd64
            runner: gha-runner-scale-set-amd64
          - platform: arm64
            runner: gha-runner-scale-set-arm64
    runs-on: ${{ matrix.runner }}
    if: ${{ inputs.PUSH_TO_PUBLIC == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: v6Org01/.github/actions/setup-buildx-privateRegistry@main
        with:
          REGISTRY: ${{ inputs.REGISTRY_PRIVATE_PULL }}
          REGISTRY_USER: ${{ secrets.REGISTRY_PRIVATE_USER }}
          REGISTRY_PASSWD: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
      - name: Login to public # to push
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY_PUBLIC }}
          username: ${{ secrets.REGISTRY_PUBLIC_USER }}
          password: ${{ secrets.REGISTRY_PUBLIC_PASSWD }}
      - name: Build and push to public
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.platform }}
          file: src/docker/Dockerfile
          push: true
          cache-from: type=gha,scope=build-${{ inputs.APPLICATION }}-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=build-${{ inputs.APPLICATION }}-${{ matrix.platform }}
          provenance: false
          build-args: ${{ inputs.BUILD_ARGS }}
          tags: |
            "${{ inputs.REGISTRY_PUBLIC }}/${{ inputs.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-${{ matrix.platform }}"

  build-merge-public:
    runs-on: gha-runner-scale-set-arm64
    needs: build-image-push-public
    steps:
      - name: Set up Docker Buildx
        uses: v6Org01/.github/actions/setup-buildx-privateRegistry@main
        with:
          REGISTRY: ${{ inputs.REGISTRY_PRIVATE_PULL }}
          REGISTRY_USER: ${{ secrets.REGISTRY_PRIVATE_USER }}
          REGISTRY_PASSWD: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
      - name: Login to public registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY_PUBLIC }}
          username: ${{ secrets.REGISTRY_PUBLIC_USER }}
          password: ${{ secrets.REGISTRY_PUBLIC_PASSWD }}
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create -t "${{ inputs.REGISTRY_PUBLIC }}/${{ inputs.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}" \
            "${{ inputs.REGISTRY_PUBLIC }}/${{ inputs.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-amd64" \
            "${{ inputs.REGISTRY_PUBLIC }}/${{ inputs.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-arm64"
      - name: Inspect image
        run: |
          docker buildx imagetools inspect "${{ inputs.REGISTRY_PUBLIC }}/${{ inputs.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}"

  ## PRIVATE ##

  build-image-push-private:
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        include:
          - platform: amd64
            runner: gha-runner-scale-set-amd64
          - platform: arm64
            runner: gha-runner-scale-set-arm64
    runs-on: ${{ matrix.runner }}
    if: ${{ inputs.PUSH_TO_PRIVATE == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: v6Org01/.github/actions/setup-buildx-privateRegistry@main
        with:
          REGISTRY: ${{ inputs.REGISTRY_PRIVATE_PULL }}
          REGISTRY_USER: ${{ secrets.REGISTRY_PRIVATE_USER }}
          REGISTRY_PASSWD: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
      - name: Login to private # to push
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY_PRIVATE }}
          username: ${{ secrets.REGISTRY_PRIVATE_USER }}
          password: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
      - name: Build and push to private
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.platform }}
          file: src/docker/Dockerfile
          push: true
          cache-from: type=gha,scope=build-${{ inputs.APPLICATION }}-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=build-${{ inputs.APPLICATION }}-${{ matrix.platform }}
          provenance: false
          build-args: ${{ inputs.BUILD_ARGS }}
          tags: |
            "${{ inputs.REGISTRY_PRIVATE }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-${{ matrix.platform }}"

  build-merge-private:
    runs-on: gha-runner-scale-set-arm64
    needs: build-image-push-private
    steps:
      - name: Set up Docker Buildx
        uses: v6Org01/.github/actions/setup-buildx-privateRegistry@main
        with:
          REGISTRY: ${{ inputs.REGISTRY_PRIVATE_PULL }}
          REGISTRY_USER: ${{ secrets.REGISTRY_PRIVATE_USER }}
          REGISTRY_PASSWD: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
      - name: Login to private # to push
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY_PRIVATE }}
          username: ${{ secrets.REGISTRY_PRIVATE_USER }}
          password: "${{ secrets.REGISTRY_PRIVATE_PASSWD }}"
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create -t "${{ inputs.REGISTRY_PRIVATE }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}" \
            "${{ inputs.REGISTRY_PRIVATE }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-amd64" \
            "${{ inputs.REGISTRY_PRIVATE }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-arm64"
      - name: Inspect image
        run: |
          docker buildx imagetools inspect "${{ inputs.REGISTRY_PRIVATE }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}"

  forward-var-version:
    runs-on: gha-runner-scale-set-arm64
    outputs:
      VERSION: ${{ steps.set-output-version.outputs.VERSION }}
    steps:
      - name: Set output VERSION
        id: set-output-version
        run: |
          echo "VERSION=${{ inputs.VERSION }}" >> $GITHUB_OUTPUT

  check-cancelled:
    runs-on: gha-runner-scale-set-arm64
    needs: build-merge-private
    outputs:
      IS_CANCELLED: ${{ steps.set-output-cancelled.outputs.IS_CANCELLED }}
    steps:
      - name: Set output IS_CANCELLED
        id: set-output-cancelled
        if: ${{ cancelled() }}
        run: |
          echo "IS_CANCELLED=true" >> $GITHUB_OUTPUT
