name: build_push

env:
  OWNER: v6org01

on:
  workflow_call:
    inputs:
      APPLICATION:
        description: 'Application for which to build container image'
        required: true
        type: string
      VERSION:
        description: 'Version to include in tag'
        required: true
        type: string
      PUSH_TO_PUBLIC:
        description: 'Push image to public registry'
        required: false
        type: string
      PUSH_TO_PRIVATE:
        description: 'Push image to private registry'
        required: false
        type: string

jobs:

  ## PUBLIC ##

  build-image-push-public:
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        include:
          - platform: amd64
            runner: gha-runner-scale-set-amd64
          - platform: arm64
            runner: gha-runner-scale-set-arm64
    runs-on: ${{ matrix.runner }}
    if: ${{ inputs.PUSH_TO_PUBLIC == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: v6Org01/.github/actions/setup-buildx-privateRegistry
      - name: Login to public # to push
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_PUBLIC }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_PACKAGES }}
      - name: Build and push to public
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.platform }}
          file: src/docker/Dockerfile
          push: true
          cache-from: type=gha,scope=build-${{ inputs.APPLICATION }}-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=build-${{ inputs.APPLICATION }}-${{ matrix.platform }}
          provenance: false
          build-args: |
            REGISTRY=${{ vars.REGISTRY_PRIVATE_PULL }}
          tags: |
            "${{ vars.REGISTRY_PUBLIC }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-${{ matrix.platform }}"

  build-merge-public:
    runs-on: gha-runner-scale-set-arm64
    needs: build-image-push-public
    steps:
      - name: Set up Docker Buildx
        uses: v6Org01/.github/actions/setup-buildx-privateRegistry
      - name: Login to public registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_PUBLIC }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_PACKAGES }}
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create -t "${{ vars.REGISTRY_PUBLIC }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}" \
            "${{ vars.REGISTRY_PUBLIC }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-amd64" \
            "${{ vars.REGISTRY_PUBLIC }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-arm64"
      - name: Inspect image
        run: |
          docker buildx imagetools inspect "${{ vars.REGISTRY_PUBLIC }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}"

  ## PRIVATE ##

  build-image-push-private:
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        include:
          - platform: amd64
            runner: gha-runner-scale-set-amd64
          - platform: arm64
            runner: gha-runner-scale-set-arm64
    runs-on: ${{ matrix.runner }}
    if: ${{ inputs.PUSH_TO_PRIVATE == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: v6Org01/.github/actions/setup-buildx-privateRegistry
      - name: Build and push to private
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.platform }}
          file: src/docker/Dockerfile
          push: true
          cache-from: type=gha,scope=build-${{ env.APPLICATION }}-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=build-${{ env.APPLICATION }}-${{ matrix.platform }}
          provenance: false
          tags: |
            "${{ vars.REGISTRY_PRIVATE }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-${{ matrix.platform }}"

  build-merge-private:
    runs-on: gha-runner-scale-set-arm64
    needs: build-image-push-private
    steps:
      - name: Set up Docker Buildx
        uses: v6Org01/.github/actions/setup-buildx-privateRegistry
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create -t "${{ vars.REGISTRY_PRIVATE }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}" \
            "${{ vars.REGISTRY_PRIVATE }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-amd64" \
            "${{ vars.REGISTRY_PRIVATE }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}-arm64"
      - name: Inspect image
        run: |
          docker buildx imagetools inspect "${{ vars.REGISTRY_PRIVATE }}/${{ env.OWNER }}/arc-${{ inputs.APPLICATION }}:${{ inputs.VERSION }}"
